economy:
# choix entre : "economyapi" ou "bedrockeconomy".
  provider: "economyapi"

# "heures:minutes"
change-bourse-time: "10:00"

message:
  sell: "Vous venez de vendre x{count} {item} pour ${amount}."
  no_sell: "Tu n'as rien à vendre."
  not_numeric: "Veuillez entrez un nombre valide."
  higher_error: "Le minimum doit être inferieur au maximum."
  edit: "L'item à bien été modifié dans la bourse."
  remove: "L'item à bien été retiré de la bourse."
  add: "L'item à été ajouté dans la bourse."
  change_bourse: "La bourse vient de changer !"

bourse:
  potato:
    display_name: "Pomme de terre"
    image_texture: "textures/items/potato"
    min: 10
    max: 20